### ISSUE TITLE
Fuzz programs that change input files

### ISSUE THREAD

**Issue by qixin5** [google/AFL#111]
Dear AFL authors,

I wonder what could be a way to use AFL to properly fuzz a program that modifies the input files provided.

I tried fuzzing bzip2 by running something like "path_to_afl-fuzz -i afl-in -o afl-out ./bzip2 @@", where ./bzip2 is a program that's compiled using afl-clang and afl-in contains a text file to be zipped. Unfortunately, I got "total paths: 1" and "(odd, check syntax!)" all the time.

I suspect that this is because bzip2 deletes the original text file (i.e., the input file for AFL) for zipping, and this makes AFL run in an unexpected way.

If so, I wonder what could be a workaround here? Thanks very much!

**Comment by ianruh** [comment]
Hi @qixin5, It looks like your problem is that bzip2 won't overwrite existing `.bz2` files be default. Add the `-f` flag ("overwrite existing output files" - from the bzip2 help text) to force it to do so.

So your command would be `afl-fuzz -i afl-in -o afl-out ./bzip2 -f @@`.
