### ISSUE TITLE
some issue about the instrumentation in LAVA-M

### ISSUE THREAD

**Issue by J-Daniel** [google/AFL#113]
Hi! When I was using afl-clang-fast to instrument the programs in the LAVA-M set, I finished `CC=~/afl-clang-fast CXX=~/afl-clang-fast++ ./configure --prefix=`pwd`/lava-install LIBS="-lacl"`, and it shows no error, and when I input `make` to get the instrumented program, I met the following error:
![image](https://user-images.githubusercontent.com/55864517/89730034-b0292b80-da6d-11ea-8b31-6b7a721a064e.png)
How can I solve this problem? I would be very grateful if you can take the time to answer this. Thanks a lot.

**Comment by Dor1s** [comment]
Can you try a newer clang? Looks like the compiler is crashing for some reason.

@lszekeres may have a better suggestion than I do.

**Comment by lszekeres** [comment]
+1 trying new llvm/clang version. what version are you currently using?

If that doesn't work, could you get and paste the stack trace of the crash?

**Comment by J-Daniel** [comment]
thxs, I reinstall my clang and solved this problem!

**Comment by Dor1s** [comment]
Awesome!
