### ISSUE TITLE
AFL beginner - Program 'guff' not found or not executable

### ISSUE THREAD

**Issue by CK213** [google/AFL#114]
Hi,

I am a beginner of AFL, I have been following the instructions on "Fuzz testing with afl-fuzz" (https://spin.atomicobject.com/2015/08/23/fuzz-testing-american-fuzzy-lop/ ).
I have compiled guff and placed it on my Desktop.
I was wondering why 'guff' is detected as not found or not executable, and how to fix this?
Note that I am running AFL on Ubuntu 16.04.7

The terminal instruction and respond are as follow. 
**~/Desktop$ afl-fuzz -i AFL/afl/in -o AFL/afl/out guff -x -lyafl-fuzz 1.96b by <lcamtuf@google.com>**
[+] You have 8 CPU cores and 1 runnable tasks (utilization: 12%).
[+] Try parallel jobs - see /usr/share/doc/afl/parallel_fuzzing.txt.
[*] Checking core_pattern...
[*] Checking CPU scaling governor...
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'AFL/afl/in'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...

**[-] PROGRAM ABORT : Program 'guff' not found or not executable
         Location : check_binary(), afl-fuzz.c:6548**

Many Thanks.

**Comment by ianruh** [comment]
Hi @CK213, I'm not sure about this, but my guess is that you need to specify the executable as `./guff` if it is just in your desktop directory, and not on your path. Generally, your current directory isn't on your path for security reasons.

**Comment by CK213** [comment]
Hi @ianruh, thanks for the fast response, and yea I have tried to specify the executable as `./guff` and `~/guff` but both execution return the same type of error.
`PROGRAM ABORT : Program './guff' not found or not executable`

**Comment by CK213** [comment]
Hi @ianruh, I have figured out my problem. I thought I needed to put the entire guff file inside AFL then run it, but I only have to put the program "guff" in.
