### ISSUE TITLE
How to use AFL for Mobile applications 

### ISSUE THREAD

**Issue by vaibhavp2** [google/AFL#122]
Can you please direct to a good tutorial that would let us know how we can use and configure this tool for a mobile application testing ? 
I have gone through the readme file but didn't quite understand how can we use for mobile application.

Thanks!

**Comment by Dor1s** [comment]
Hi @vaibhavp2,

It might be useful to learn more about fuzzing first. You can check https://github.com/google/fuzzing, http://tutorial.libfuzzer.info/, https://github.com/Dor1s/libfuzzer-workshop or any other blogs / videos on the topic. That would give you a better understanding of what's fuzzable and what's not. "Fuzzing a mobile application" sounds very vague. I'd suggest to better understand / identify the actual target you're going to fuzz and go from there.
