### ISSUE TITLE
Merge network fuzzing code

### ISSUE THREAD

**Issue by originalsouth** [google/AFL#34]
The [AFL fork](https://github.com/jdbirdwell/afl) by @jdbirdwell, contains code for network fuzzing. Perhaps it would be nice to merge this to the mainline?

**Comment by vanhauser-thc** [comment]
to chime in here: this is a horrible, horrible idea :-)

I ported an enhanced version of that old network code into afl++ here: https://github.com/vanhauser-thc/AFLplusplus/tree/networking
try it out, and you will see the performance loss is really bad. like really really bad. the network stuff makes it slow. if you rather edit the code to read from stdin instead, this will be so much faster.
And even without touching the code you can use the desock2 preload libraray from the preeny project and have a similar speed to the "change code to read from stdin".

if you *need* the networking code (e.g. blackbox binary fuzzing with qemu or afl-dyninst), then use that branch I linked. it has everything afl 2.55b has, plus the network code, is faster and has more features.

**Comment by originalsouth** [comment]
> **https://github.com/google/AFL/issues/34#issuecomment-534011655**

Thanks for the feedback. Now that I am aware of AFLplusplus -- which is great work by the way -- perhaps an issue should be raised to merge AFLplusplus back into this repo :+1: as you state this is unlikely to happen...
I will start playing with AFLplusplus :-)

This resolves the issue for me.

**Comment by vanhauser-thc** [comment]
@originalsouth I think merging is difficult. you can open an issue at the google/afl tracker though :)

**Comment by jonathanmetzman** [comment]
AFLplusplus refactored a lot so I agree upstreaming changes will be difficult. But we may look at upstreaming some features in the future.
