### ISSUE TITLE
AFL algorithm

### ISSUE THREAD

**Issue by 21212124** [google/AFL#55]
I would like to know where is the part of the afl algorithm where the seeds change. Where is it implemented? Does it change randomly?

**Comment by NapongiZero** [comment]
TLDR; There are numerous fuzzing strategies being used (bit/byte flips, splicing and more).
You can find out how inputs are mutated at chapter _**6) Fuzzing strategies**_ from https://github.com/google/AFL/blob/master/docs/technical_details.txt

As to where it's implemented, check afl-fuzz.c (Prepare yourself, it's overwhelming)
https://github.com/google/AFL/blob/master/afl-fuzz.c

**Comment by 21212124** [comment]
> En cuanto a dónde se implementa, verifique afl-fuzz.c (Prepárese, es abrumador)
> https://github.com/google/AFL/blob/master/afl-fuzz.c

You don't know where it is implemented?

**Comment by jonathanmetzman** [comment]
> > En cuanto a dónde se implementa, verifique afl-fuzz.c (Prepárese, es abrumador)
> > https://github.com/google/AFL/blob/master/afl-fuzz.c
> 
> You don't know where it is implemented? It is hard to find?

Looks like it is somewhere here: https://github.com/google/AFL/blob/master/afl-fuzz.c#L6128
