### ISSUE TITLE
Multiple input files for fuzzing

### ISSUE THREAD

**Issue by maratdin7** [google/AFL#57]
Hello, 
I would like to know if the AFL has the ability to use multiple files for input. 

The program reads part of the data from the stdin, and the second part-from any file.

Can I fuzz such a program?
I know that  the AFL does not support this, but maybe there are some tricks?

thank you very much

**Comment by jonathanmetzman** [comment]
You could write a harness that reads input from AFL (via stdin) for example, then use FuzzedDataProvider ([explanation](https://github.com/google/fuzzing/blob/master/docs/split-inputs.md#how-to-split-a-fuzzer-generated-input-into-several)) to split the input and feed it to the parts of the program that accept input.
