### ISSUE TITLE
How do I get the standard output of the program being tested?

### ISSUE THREAD

**Issue by NikParam42** [google/AFL#71]
Hi! Tell me please
How do I access `stderr` `stdout` of the program we are testing?

I compiled my program this way (using memory sanitizer): 

> afl-gcc -fsaninite=address -g main.c -o myprog

Next, I run the fuzzer, but how do I get stderr `myprog` ??

**Comment by jonathanmetzman** [comment]
You need to modify the program to output stdout and stderr to a location you desire.
[afl_driver.cpp](https://github.com/llvm-mirror/compiler-rt/blob/master/lib/fuzzer/afl/afl_driver.cpp) does this.
