### ISSUE TITLE
In AFL dumb mode, how do afl feeds input to target?

### ISSUE THREAD

**Issue by guilanl** [google/AFL#78]
Without instrumentation info, how do AFL generate input for target?

**Comment by tuanhtrng** [comment]
stdin or fin.

**Comment by jonathanmetzman** [comment]
I'm not 100% what you are asking. Maybe the last comment helps. But if youre asking about how mutation happens without instrumentation.
I don't think instrumentation changes mutation at all. It just changes whether those inputs can be "evolved" on. So I think the mutations should be the same with or without instrumentation.

**Comment by jonathanmetzman** [comment]
Feel free to reopen and clarify the question if this doesn't answer it.
