### ISSUE TITLE
Symbol lookup error while build llvm_mode.

### ISSUE THREAD

**Issue by runfengxu** [google/AFL#90]
make: Entering directory '/home/runfeng/afl-2.52b/llvm_mode'
[*] Checking for working 'llvm-config'...
[*] Checking for working 'clang-6.0'...
[*] Checking for '../afl-showmap'...
[+] All set and ready to build.
[*] Building 32-bit variant of the runtime (-m32)... failed (that's fine)
[*] Testing the CC wrapper and instrumentation output...
unset AFL_USE_ASAN AFL_USE_MSAN AFL_INST_RATIO; AFL_QUIET=1 AFL_PATH=. AFL_CC=clang-6.0 ../afl-clang-fast -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"2.52b\"  ../test-instr.c -o test-instr 
/usr/lib/llvm-6.0/bin/clang: symbol lookup error: ../afl-llvm-pass.so: undefined symbol: _ZN4llvm8LoadInstC1EPNS_4TypeEPNS_5ValueERKNS_5TwineEPNS_11InstructionE
clang: error: unable to execute command: No such file or directory
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: error: unable to execute command: No such file or directory
clang: note: diagnostic msg: Error generating preprocessed source(s).
Makefile:97: recipe for target 'test_build' failed
make: *** [test_build] Error 255
make: Leaving directory '/home/runfeng/afl-2.52b/llvm_mode'

---
I tried  clang-4.0,clang-6.0,clang-9,clang-10 and llvm-4,6,10 .All those versions causes this same bug.

**Comment by jonathanmetzman** [comment]
Try setting LLVM_CONFIG to point to the llvm-config binary that coresponds to the same clang you are using to compile llvm mode.
I'm pretty sure this isn't issue with the code itself and the issue is caused by something incorrect in your set up. I get similar errors myself until I correct things.
